name: signalbutton
description: push button signal simulator
publish_to: 'none'
version: 1.2.2+22

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  # Audio Player
  audioplayers: ^6.0.0
  # Vibration
  vibration: ^1.9.0
  # Text to Speech
  flutter_tts: ^4.0.2
  # Settings
  flutter_settings_screens: ^0.3.4
  settings_ui: ^2.0.2
  # SharedPreference
  shared_preferences: ^2.2.3
  # Admob
  google_mobile_ads: ^5.1.0
  app_tracking_transparency: ^2.0.5
  # Device locale
  devicelocale: ^0.7.1
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  #env
  flutter_dotenv: ^5.1.0
  #Revenue Cat
  purchases_flutter: ^6.30.1
  #MVVM
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # App Splash
  flutter_native_splash: ^2.4.1

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#373635"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/human.png"
  color: "373635"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pedestrian/us/
    - assets/images/pedestrian/jp/
    - assets/images/pedestrian/uk/
    - assets/images/pedestrian/au/
    - assets/images/traffic/us/
    - assets/images/traffic/jp/
    - assets/images/traffic/uk/
    - assets/images/traffic/au/
    - assets/audios/
    - assets/.env

  fonts:
    - family: freeTfb
      fonts:
        - asset: assets/fonts/freetfb.ttf
    - family: beon
      fonts:
        - asset: assets/fonts/beon.ttf
