name: signalbutton
description: push button signal simulator
publish_to: 'none'
version: 1.1.8+18

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  # App Icon
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.12.0
  # Audio Player
  audioplayers: ^3.0.1
  # Vibration
  vibration: ^1.7.6
  # Text to Speech
  flutter_tts: ^3.6.3
  # Settings
  flutter_settings_screens: ^0.3.3-null-safety+2
  settings_ui: ^2.0.2
  # SharedPreference
  shared_preferences: ^2.0.20
  # Admob
  google_mobile_ads: ^2.4.0
  app_tracking_transparency: ^2.0.3
  # Device locale
  devicelocale: ^0.6.0
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  #env
  flutter_dotenv: ^5.0.2
  # Connectivity
  connectivity_plus: ^4.0.1
  #Revenue Cat
  purchases_flutter: ^4.11.1
  #MVVM
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # App Splash
  flutter_native_splash: ^2.2.19

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#373635"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/human.png"
  color: "373635"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pedestrian/us/
    - assets/images/pedestrian/jp/
    - assets/images/pedestrian/uk/
    - assets/images/pedestrian/au/
    - assets/images/traffic/us/
    - assets/images/traffic/jp/
    - assets/images/traffic/uk/
    - assets/images/traffic/au/
    - assets/audios/
    - assets/.env

  fonts:
    - family: freeTfb
      fonts:
        - asset: assets/fonts/freetfb.ttf
    - family: beon
      fonts:
        - asset: assets/fonts/beon.ttf
