name: signalbutton
description: push button signal simulator
publish_to: 'none'
version: 1.0.7+7

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^1.24.0
  firebase_analytics: ^9.3.8
  # App Icon
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.10.0
  # Audio Player
  audioplayers: ^0.20.0
  # Vibration
  vibration: ^1.7.6
  # Text to Speech
  flutter_tts: ^3.5.3
  # Settings
  flutter_settings_screens: ^0.3.3-null-safety+2
  # SharedPreference
  shared_preferences: ^2.0.15
  # Device Info
  device_info_plus: ^5.0.5
  # Admob
  google_mobile_ads: ^2.0.1
  app_tracking_transparency: ^2.0.2+4
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  #env
  flutter_dotenv: ^5.0.2
  #Revenue Cat
  purchases_flutter: ^4.3.1
  #MVVM
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # App Splash
  flutter_native_splash: ^2.2.10+1

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#373635"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/human.png"
  color: "373635"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pedestrian/us/
    - assets/images/pedestrian/jp/
    - assets/images/pedestrian/uk/
    - assets/images/pedestrian/au/
    - assets/images/traffic/us/
    - assets/images/traffic/jp/
    - assets/images/traffic/uk/
    - assets/images/traffic/au/
    - assets/audios/
    - .env

  fonts:
    - family: freeTfb
      fonts:
        - asset: assets/fonts/freetfb.ttf
    - family: beon
      fonts:
        - asset: assets/fonts/beon.ttf
