name: signalbutton
description: push button signal simulator
publish_to: 'none'
version: 1.2.0+19

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^2.20.0
  firebase_analytics: ^10.6.2
  # App Icon
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  # Audio Player
  audioplayers: ^5.2.0
  # Vibration
  vibration: ^1.8.3
  # Text to Speech
  flutter_tts: ^3.8.3
  # Settings
  flutter_settings_screens: ^0.3.3-null-safety+2
  settings_ui: ^2.0.2
  # SharedPreference
  shared_preferences: ^2.2.2
  # Admob
  google_mobile_ads: ^3.1.0
  app_tracking_transparency: ^2.0.4
  # Device locale
  devicelocale: ^0.7.0
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  #env
  flutter_dotenv: ^5.1.0
  # Connectivity
  connectivity_plus: ^5.0.1
  #Revenue Cat
  purchases_flutter: ^5.8.0
  #MVVM
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # App Splash
  flutter_native_splash: ^2.3.4

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#373635"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/human.png"
  color: "373635"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pedestrian/us/
    - assets/images/pedestrian/jp/
    - assets/images/pedestrian/uk/
    - assets/images/pedestrian/au/
    - assets/images/traffic/us/
    - assets/images/traffic/jp/
    - assets/images/traffic/uk/
    - assets/images/traffic/au/
    - assets/audios/
    - assets/.env

  fonts:
    - family: freeTfb
      fonts:
        - asset: assets/fonts/freetfb.ttf
    - family: beon
      fonts:
        - asset: assets/fonts/beon.ttf
